---
movie:
- id: 1
  name: "The Avengers"
  stockCount: 0
  type: 2
- id: 2
  name: "Shawshank Redemption"
  stockCount: 80
  type: 3
- id: 3
  name: "Aquaman"
  stockCount: 9
  type: 1
- id: 50
  name: "Spider-Man: Into the Spider-Verse"
  stockCount: 0
  type: 1
- id: 214
  name: "The Upside"
  stockCount: 0
  type: 1
- id: 25
  name: "The Kid Who Would Be King"
  stockCount: 3
  type: 2
- id: 26
  name: "Forrest Gump"
  stockCount: 2
  type: 3
- id: 27
  name: "The Dark Knight"
  stockCount: 11
  type: 2
- id: 125
  name: "Schindler's List"
  stockCount: 7
  type: 3
- id: 130
  name: "The Lord of the Rings: The Two Towers"
  stockCount: 2
  type: 2
- id: 131
  name: "Whiplash"
  stockCount: 8
  type: 2
- id: 12
  name: "The Intouchables"
  stockCount: 1
  type: 2
- id: 215
  name: "test"
  stockCount: 0
  type: 1
customer:
- id: 1
  name: "Maria Kusk"
  points: 322
- id: 2
  name: "Kristian Vehmas"
  points: 0
- id: 3
  name: "Irina Tamm"
  points: 455
- id: 5
  name: "Mikk Saar"
  points: 25
- id: 6
  name: "test"
  points: 0
- id: 7
  name: "test"
  points: 0
order:
- id: 1
  customer: 2
  orderDate:
  - 2019
  - 1
  - 20
  items:
  - movie: 3
    type: 1
    days: 15
    paidByBonus: false
    returnedDay: null
  - movie: 26
    type: 3
    days: 2
    paidByBonus: true
    returnedDay: null
- id: 2
  customer: 3
  orderDate:
  - 2020
  - 3
  - 2
  items:
  - movie: 1
    type: 2
    days: 7
    paidByBonus: false
    returnedDay:
    - 2020
    - 3
    - 5
- id: 4
  customer: 2
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 1
    paidByBonus: false
    returnedDay:
    - 2020
    - 3
    - 5
- id: 5
  customer: 3
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 5
    paidByBonus: false
    returnedDay: null
- id: 6
  customer: 3
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 5
    paidByBonus: true
    returnedDay: null
- id: 7
  customer: 2
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 5
    paidByBonus: true
    returnedDay:
    - 2020
    - 3
    - 5
- id: 8
  customer: 2
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 5
    paidByBonus: false
    returnedDay:
    - 2020
    - 3
    - 5
- id: 9
  customer: 2
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 25
    type: 2
    days: 5
    paidByBonus: false
    returnedDay: null
  - movie: 3
    type: 1
    days: 5
    paidByBonus: false
    returnedDay: null
- id: 10
  customer: 3
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 3
    type: 1
    days: 1
    paidByBonus: true
    returnedDay:
    - 2020
    - 3
    - 5
- id: 11
  customer: 1
  orderDate:
  - 2020
  - 3
  - 5
  items:
  - movie: 2
    type: 3
    days: 1
    paidByBonus: false
    returnedDay: null
  - movie: 3
    type: 1
    days: 2
    paidByBonus: false
    returnedDay: null
- id: 12
  customer: 2
  orderDate:
  - 2020
  - 3
  - 6
  items:
  - movie: 2
    type: 3
    days: 5
    paidByBonus: false
    returnedDay: null
- id: 13
  customer: 2
  orderDate:
  - 2020
  - 3
  - 6
  items:
  - movie: 2
    type: 3
    days: 6
    paidByBonus: false
    returnedDay: null
- id: 14
  customer: 2
  orderDate:
  - 2020
  - 3
  - 6
  items:
  - movie: 2
    type: 3
    days: 6
    paidByBonus: false
    returnedDay: null
- id: 15
  customer: 2
  orderDate:
  - 2020
  - 3
  - 6
  items:
  - movie: 2
    type: 3
    days: 5
    paidByBonus: false
    returnedDay: null
- id: 16
  customer: 2
  orderDate:
  - 2020
  - 3
  - 6
  items:
  - movie: 2
    type: 3
    days: 5
    paidByBonus: false
    returnedDay: null
